import Head from 'next/head'
import Dashboard from '../Components/Dashboard'
import Login from '../Components/Login';
import styles from '../styles/Home.module.css';
import {getSession , useSession, getProviders} from 'next-auth/react';

export default function Home({providers}) {
  const { data:session } = useSession();
  
  if(!session) return <Login providers = {providers} />
  return (
    <div className={styles.container}>
      <Head>
        <title>Re-Bin </title>
        <meta name="description" content="Food Donation app Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    
      </Head>

      <main>
        <Dashboard  />
      </main>
     
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  const providers = await getProviders();
  return{
    props:{
      session,
      providers
    }
  }

}
